name: CI Check

on: [ push ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11
          cache: gradle
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Check
        run: ./gradlew check
        env:
          ORG_GRADLE_PROJECT_hivemqEnterpriseAccessKey: ${{ secrets.HIVEMQ_ENTERPRISE_KEY }}
          ORG_GRADLE_PROJECT_hivemqEnterpriseSecretKey: ${{ secrets.HIVEMQ_ENTERPRISE_SECRET }}